paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Todos los productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Error del servidor
    post:
      summary: Crear producto
      tags:
        - Products
      requestBody:
        content:
          application/json:
            example:
              status: true
              title: "Nuevo producto"
              description: "Descripción del nuevo producto"
              price: 29.99
              code: "ABC123"
              stock: 50
              category: "Electrónicos"
            schema:
              $ref: "#/components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error del servidor
        "400":
          description: Faltan algunos datos

  /api/products/{pid}:
    get:
      summary: Obtener producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado con el ID proporcionado
        "500":
          description: Error del servidor

    delete:
      summary: Eliminar producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado
        "404":
          description: Producto no encontrado con el ID proporcionado
        "500":
          description: Error del servidor

    put:
      summary: Actualizar producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              status: true
              title: "Producto actualizado"
              description: "Nueva descripción del producto"
              price: 39.99
              code: "XYZ789"
              stock: 60
              category: "Electrónicos"
            schema:
              $ref: "#/components/requestBodies/updateProduct"
      responses:
        "200":
          description: Producto actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado con el ID proporcionado
        "500":
          description: Error del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        status:
          type: boolean
          description: Estado del producto
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        code:
          type: string
          description: Código del producto
        stock:
          type: number
          description: Stock del producto
        category:
          type: string
          description: Categoría del producto
      required:
        - title
        - description
        - code
        - price
        - stock
        - category

  requestBodies:
    createProduct:
      required: true
      content:
        application/json:
          example:
            status: true
            title: "Nuevo producto"
            description: "Descripción del nuevo producto"
            price: 29.99
            code: "ABC123"
            stock: 50
            category: "Electrónicos"
          schema:
            $ref: "#/components/schemas/Product"
    updateProduct:
      required: true
      content:
        application/json:
          example:
            status: true
            title: "Producto actualizado"
            description: "Nueva descripción del producto"
            price: 39.99
            code: "XYZ789"
            stock: 60
            category: "Electrónicos"
          schema:
            $ref: "#/components/schemas/Product"
